language: node_js

node_js:
  - "8.11.4"

os:
  - linux

env:
  - PATH=$PATH:/home/travis/.nvm/versions/node/v8.11.4/bin/

sudo: required

dist: wheezy

install:
  - npm install

script:
  - npm test
